FORMAT: 1A
HOST: http://api.cakesnaps.com/api/v1/

# api.cakesnaps.com

Cakesnaps is built for anyone who bakes or appreciates good looking food. 
Share snaps of your latest baking creations, ideas or experiments and receive feedback.

# Group Cakes
Resources related to cakes in API.
## Cakes List [/cakes?{me}&{favorites}&{likes}&{love}&{type}&{theme}&{pages}]

+ Parameters

    + me (optional, id) - Id of user who owns cakes. It will list all cakes of user.
    + favorites (optional, boolean) - It will list favorited cakes.
    + likes (optional, boolean) - It will list all liked cakes.
    + love (optional, boolean) - It will list all loved cakes.
    + type (optional, string) - Filter all cakes according to category.
    + theme (optional, string) - Filter all cakes according to theme.
    + pages (optional, int) - Display specific page according to specified page number.

### Get cakes [GET]
Display all list of cakes.

+ Response 200 (application/json)


        {
            "data": [
                {
                    "id": "cc093a40-0f6e-11e7-a064-69c053d82853",
                    "name": "Ea repudiandae possimus aut dolorum.",
                    "description": "Voluptatibus vero voluptatum tenetur sed perspiciatis labore inventore. Totam minima consectetur voluptatem placeat doloribus voluptatum quos. Est suscipit explicabo provident ea.",
                    "picture_url": "http://lorempixel.com/720/500/?52395",
                    "slug": "ea-repudiandae-possimus-aut-dolorum",
                    "created_at": "2017-03-23 02:17:00",
                    "created_at_human": "23 seconds ago",
                    "user": {
                        "data": {
                            "id": "cc0499d0-0f6e-11e7-b27e-f397ec55e802",
                            "name": "Ms. Heather Gutmann",
                            "email": "cletus99@example.org",
                            "gender": "female",
                            "timezone": -8,
                            "location": null,
                            "picture_url": "http://lorempixel.com/640/480/?85209",
                            "thumbnail": null,
                            "bio": "Accusantium nesciunt nesciunt nihil eligendi reiciendis natus et autem omnis ipsam quos fugit impedit aut nihil soluta et assumenda eos nemo laborum incidunt dolorum vero accusantium consequuntur expedita dolorum dolores nihil sed velit tenetur voluptas ut eos quia est molestiae rem occaecati et nesciunt deserunt deleniti sint qui id animi dolor qui amet pariatur est mollitia animi eius earum minima aut sint dolor officiis debitis reprehenderit possimus officiis sed amet eum qui in odit omnis harum error molestias nulla voluptatum necessitatibus qui et laborum repudiandae voluptas aut ut placeat enim pariatur voluptatem dolor hic odio hic dolor minus odit nobis laborum aliquid sapiente dolore doloribus quis molestias facere facilis consequatur et officiis impedit dolorem assumenda sint dolor facilis.",
                            "birthdate": null
                        }
                    }
                }
            ],
            "meta": {
                
                "pagination": {
                    "total": 1,
                    "count": 1,
                    "per_page": 5,
                    "current_page": 1,
                    "total_pages": 1,
                    "links": [
                        "next": "http://api.cakesnaps.com/api/v1/cakes?page=2"
                    ]
                    
                }
            
            }
        }
        
## Create New Cake [/cakes]

### Post Cake [POST]

Authenticated users can able to create a cake instance using this action.
User's may upload an image during this action.

+ Request (application/json)

    + Headers
            
            Accept: application/json
    
    + Body

            {
                "name": "First Cake",
                "description": "Cakes description",
                "image": "cake.jpg"
            }

+ Response 201 (application/json)


    + Body

            {
                "data": [
                    {
                        "id": "cc093a40-0f6e-11e7-a064-69c053d82853",
                        "name": "Ea repudiandae possimus aut dolorum.",
                        "description": "Voluptatibus vero voluptatum tenetur sed perspiciatis labore inventore. Totam minima consectetur voluptatem placeat doloribus voluptatum quos. Est suscipit explicabo provident ea.",
                        "picture_url": "http://lorempixel.com/720/500/?52395",
                        "slug": "ea-repudiandae-possimus-aut-dolorum",
                        "created_at": "2017-03-23 02:17:00",
                        "created_at_human": "23 seconds ago",
                        "user": {
                            "data": {
                                "id": "cc0499d0-0f6e-11e7-b27e-f397ec55e802",
                                "name": "Ms. Heather Gutmann",
                                "email": "cletus99@example.org",
                                "gender": "female",
                                "timezone": -8,
                                "location": null,
                                "picture_url": "http://lorempixel.com/640/480/?85209",
                                "thumbnail": null,
                                "bio": "Accusantium nesciunt nesciunt nihil eligendi reiciendis natus et autem omnis ipsam quos fugit impedit aut nihil soluta et assumenda eos nemo laborum incidunt dolorum vero accusantium consequuntur expedita dolorum dolores nihil sed velit tenetur voluptas ut eos quia est molestiae rem occaecati et nesciunt deserunt deleniti sint qui id animi dolor qui amet pariatur est mollitia animi eius earum minima aut sint dolor officiis debitis reprehenderit possimus officiis sed amet eum qui in odit omnis harum error molestias nulla voluptatum necessitatibus qui et laborum repudiandae voluptas aut ut placeat enim pariatur voluptatem dolor hic odio hic dolor minus odit nobis laborum aliquid sapiente dolore doloribus quis molestias facere facilis consequatur et officiis impedit dolorem assumenda sint dolor facilis.",
                                "birthdate": null
                            }
                        }
                    }
                ]
            }
         
##  Cake [/cake/{slug}]

+ Parameters 

    + slug (string) - Slug of cake in the form of string
    
### Display a Single Cake [GET]

It will show a single cake details.

+ Request (application/json)

    + Headers
        
            Accept: application/json
        
    
+ Response 200 (application/json)

        {
        
            "data": [
                {
                    "id": "cc093a40-0f6e-11e7-a064-69c053d82853",
                    "name": "Ea repudiandae possimus aut dolorum.",
                    "description": "Voluptatibus vero voluptatum tenetur sed perspiciatis labore inventore. Totam minima consectetur voluptatem placeat doloribus voluptatum quos. Est suscipit explicabo provident ea.",
                    "picture_url": "http://lorempixel.com/720/500/?52395",
                    "slug": "ea-repudiandae-possimus-aut-dolorum",
                    "created_at": "2017-03-23 02:17:00",
                    "created_at_human": "23 seconds ago",
                    "user": {
                        "data": {
                            "id": "cc0499d0-0f6e-11e7-b27e-f397ec55e802",
                            "name": "Ms. Heather Gutmann",
                            "email": "cletus99@example.org",
                            "gender": "female",
                            "timezone": -8,
                            "location": null,
                            "picture_url": "http://lorempixel.com/640/480/?85209",
                            "thumbnail": null,
                            "bio": "Accusantium nesciunt nesciunt nihil eligendi reiciendis natus et autem omnis ipsam quos fugit impedit aut nihil soluta et assumenda eos nemo laborum incidunt dolorum vero accusantium consequuntur expedita dolorum dolores nihil sed velit tenetur voluptas ut eos quia est molestiae rem occaecati et nesciunt deserunt deleniti sint qui id animi dolor qui amet pariatur est mollitia animi eius earum minima aut sint dolor officiis debitis reprehenderit possimus officiis sed amet eum qui in odit omnis harum error molestias nulla voluptatum necessitatibus qui et laborum repudiandae voluptas aut ut placeat enim pariatur voluptatem dolor hic odio hic dolor minus odit nobis laborum aliquid sapiente dolore doloribus quis molestias facere facilis consequatur et officiis impedit dolorem assumenda sint dolor facilis.",
                            "birthdate": null
                        }
                    }
                }
            ]
        }



## Update Cake [/cake]

### Change cake's details [PUT]

Updates cake details, including cake's image.

+ Request (application/json)

    + Headers
    
            Accept: application/json
            
    + Body
    
            {
            
                "name": "Updated cake",
                "description": "Updated description.",
                "image": "anothercakesimage.jpg"
            }


+ Response 201 (application/json)

            {
                "data": [
                    {
                        "id": "cc093a40-0f6e-11e7-a064-69c053d82853",
                        "name": "Updated cake.",
                        "description": "Updated description",
                        "picture_url": "http://lorempixel.com/720/500/?52395",
                        "slug": "updated-cake",
                        "created_at": "2017-03-23 02:17:00",
                        "created_at_human": "2 seconds ago",
                        "user": {
                            "data": {
                                "id": "cc0499d0-0f6e-11e7-b27e-f397ec55e802",
                                "name": "Ms. Heather Gutmann",
                                "email": "cletus99@example.org",
                                "gender": "female",
                                "timezone": -8,
                                "location": null,
                                "picture_url": "http://lorempixel.com/640/480/?85209",
                                "thumbnail": null,
                                "bio": "Accusantium nesciunt nesciunt nihil eligendi reiciendis natus et autem omnis ipsam quos fugit impedit aut nihil soluta et assumenda eos nemo laborum incidunt dolorum vero accusantium consequuntur expedita dolorum dolores nihil sed velit tenetur voluptas ut eos quia est molestiae rem occaecati et nesciunt deserunt deleniti sint qui id animi dolor qui amet pariatur est mollitia animi eius earum minima aut sint dolor officiis debitis reprehenderit possimus officiis sed amet eum qui in odit omnis harum error molestias nulla voluptatum necessitatibus qui et laborum repudiandae voluptas aut ut placeat enim pariatur voluptatem dolor hic odio hic dolor minus odit nobis laborum aliquid sapiente dolore doloribus quis molestias facere facilis consequatur et officiis impedit dolorem assumenda sint dolor facilis.",
                                "birthdate": null
                            }
                        }
                    }
                ]
            }
            
## Delete Cake [/cakes/{slug}]

+ Parameters
    + slug (string) - Slug of cake in the form of string

### Remove cake [DELETE]
Administrator may remove created cake using this action if rules 
has been violated by the user.

+ Response 204 (application/json)

#Group Categories
Resources related to categories of cakes in API.

## Categories List [/categories?{pages}]
+ Parameters

    + pages (optional, int) - Display specific page according to specified page number.

### Get Categories [GET]
Display all categories of cakes.

+ Response 200 (application/json)

        {
        
            "data": [
            
                {
                    "name": "First Category",
                    "description": "First Category description",
                    "slug": "first-category"
                },
                {
                    "name": "Second Category",
                    "description": "Second Category description",
                    "slug": "second-category"
                }   
            
            ],
            "meta": {
                "pagination": {
                    "total": 2,
                    "count": 2,
                    "per_page": 10,
                    "current_page":1,
                    "total_pages": 1,
                    "links": {
                        "next": "http://api.cakesnaps.com/api/v1/categories?page=2"
                    }
                }
                
            }
            
        }
        
## Category [/category/{slug}]
+ Parameters

    + slug (string) - Slug of category in the form of string
    
### Display a Single Category[GET]
This action will display a specific category and show all related cakes.

+ Response 200 (application/json)

        {
        
            "data": [
            
                "name": "First Category",
                "description": "First Category description",
                "slug": "first-category",
                "cakes": {
                
                    "data": [
                    
                        {"id": "cc093a40-0f6e-11e7-a064-69c053d82853",
                        "name": "First Cake.",
                        "description": "Voluptatibus vero voluptatum tenetur sed perspiciatis labore inventore. Totam minima consectetur voluptatem placeat doloribus voluptatum quos. Est suscipit explicabo provident ea.",
                        "picture_url": "http://lorempixel.com/720/500/?52395",
                        "slug": "first-cake",
                        "created_at": "2017-03-23 02:17:00",
                        "created_at_human": "23 seconds ago"
                    ]
                }
            ]
        }
        
## Create New Category [/categories]

### Post Category [POST]
Administrator can able to create categories of cake.

+ Request (application/json)

    + Headers
        
            Accept: application/json
        
    + Body 
    
            {
            
                "name": "Create category",
                "description": "Create category description"
                
            }
+ Response 201 (application/json)

        {
        
            "data": [
            
                "name": "First Category",
                "description": "First Category description",
                "slug": "first-category"
                "cakes": {
                
                    "data": [
                    
                        "id": "cc093a40-0f6e-11e7-a064-69c053d82853",
                        "name": "First Cake.",
                        "description": "Voluptatibus vero voluptatum tenetur sed perspiciatis labore inventore. Totam minima consectetur voluptatem placeat doloribus voluptatum quos. Est suscipit explicabo provident ea.",
                        "picture_url": "http://lorempixel.com/720/500/?52395",
                        "slug": "first-cake",
                        "created_at": "2017-03-23 02:17:00",
                        "created_at_human": "23 seconds ago"
                    ]
                }
            ]
        }
        
## Update Category [/categories/{slug}]
+ Parameters 
    + slug: `first-category` - The unique slug of category.

### Change category details [PUT]

Administrator can able to update categories detail.

+ Request

    + Headers
         
            Accept: application/json
        
        
    + Body
    
            {
            
                "name": "Update category",
                "description": "Update category's description"
            }
            
+ Response 201 (application/json)

        {
            "data": {
                "name": "Updated Category Name.",
                "description": "Cum tenetur et ut quaerat voluptas. Ea quia aut aliquid impedit qui. Autem alias iusto odio dolorem aperiam.",
                "slug": "updated-category-name",
                "cakes": {
                    "data": [
                        {
                          "id": "057be8f0-1066-11e7-8df0-45dcddb25cd6",
                          "name": "Soluta temporibus sint sit voluptatem iusto aut consequuntur et.",
                          "description": "Vel saepe omnis quae accusamus dolorum modi nostrum. Officiis quas in eos corrupti quod. Voluptas provident ut ipsa laudantium.",
                          "picture_url": "http://lorempixel.com/720/500/?24316",
                          "slug": "soluta-temporibus-sint-sit-voluptatem-iusto-aut-consequuntur-et",
                          "created_at": "2017-03-24 07:46:42",
                          "created_at_human": "51 minutes ago"
                        },
                        {
                          "id": "057cd2d0-1066-11e7-9c8f-373efb7398f8",
                          "name": "Voluptatibus et nulla eligendi necessitatibus et sed.",
                          "description": "Ipsa sint nulla non esse accusamus quo aliquid et. Occaecati necessitatibus sint quod est.",
                          "picture_url": "http://lorempixel.com/720/500/?49516",
                          "slug": "voluptatibus-et-nulla-eligendi-necessitatibus-et-sed",
                          "created_at": "2017-03-24 07:46:42",
                          "created_at_human": "51 minutes ago"
                        }
                    ]
                }
            }
        }
        
#Group User  
Resources related to Users.

## User List [/users?{active}&{suspended}]
+ Parameters

    + active (optional, boolean) - List all active users.
    + suspended (optional, boolean) - List all suspended users.
    
### Get Users [GET]

Administrator can view all users depending on their status.

+ Request 

    + Headers
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

        {
        
            "data" : [
            
                {
                    "id": "055312e0-1066-11e7-b474-4dcaafd259a6",
                    "name": "Demetrius Herman",
                    "email": "volkman.edna@example.org",
                    "gender": "female",
                    "timezone": -7,
                    "location": "Port Emily, New York",
                    "picture_url": "http://lorempixel.com/640/480/?16665",
                    "thumbnail": null,
                    "bio": "Omnis tenetur totam itaque reiciendis sed vero culpa in odio ducimus et est corporis nesciunt hic non quidem aperiam quasi magni et voluptatum doloremque tempora veritatis omnis voluptas numquam debitis pariatur sit nesciunt commodi ab quia in sit aut ut ut exercitationem et quis sit repellat velit est officiis cum itaque fuga rem rerum iste rerum assumenda cum impedit provident rem temporibus dolorem vel sapiente cumque magnam velit ducimus ea et quas perferendis at voluptate et aperiam qui omnis dicta impedit neque.",
                    "birthdate": null,
                    "cakes": {
                        "data": []
                    }
                },
                {
                
                    "id": "056822f0-1066-11e7-9463-254ec642b045",
                    "name": "Jacquelyn Gaylord",
                    "email": "sydney.gutkowski@example.org",
                    "gender": "female",
                    "timezone": -2,
                    "location": "New Kristoferfurt, Michigan",
                    "picture_url": "http://lorempixel.com/640/480/?57874",
                    "thumbnail": null,
                    "bio": "Nostrum id cupiditate iusto dolore omnis esse dicta labore molestias qui quasi nobis sint nulla in quod asperiores officia non consequatur incidunt amet numquam iste voluptatem cumque magni dicta et impedit mollitia aperiam dicta sunt voluptatibus aspernatur reprehenderit et sed soluta minus iste sequi sed maxime quasi blanditiis autem vel explicabo aperiam tempore adipisci est rerum tempore culpa et eos repudiandae ipsa non et soluta nesciunt distinctio a eveniet aperiam quidem error dicta sapiente maiores nam officiis nihil at sed eum quasi nemo voluptatem porro non error eum enim.",
                    "birthdate": null,
                    "cakes": {
                        "data": []
                    }
                }
            ], 
            
            "meta" : {
            
                "pagination": {
                    "total": 2,
                    "count": 20,
                    "per_page": 20,
                    "current_page": 1,
                    "total_pages": 4,
                    "links": {
                        "next": "http://api.cakesnaps.com/api/v1/users?page=2"
                    }
                }
            }
        }

## Get User [/user]
Will fetch a single user.

### Display User [GET]

+ Request 

    + Headers 
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

    + Attributes
        - users (User Full)
## Update User [/user/123df]        
### PUT 
+ Request (application/json)

    + Attributes
    
        - users (User Full)
        
+ Response 201 (application/json)

    + Attributes
    
        - users (User Full)
        
# Data Structures

## User Create (object)
- name: `Jearson Gomez` (string,required) - Name of user.
- email: `4ksoftware@example.io` (string, required) - Email of user.
- active: true (boolean, optional) - Status of user account.
- gender: `male` (string, optional) - Gender of user.
- timezone: 8 (number, optional) - Region of user who uploaded/created cake page.
- picture_url: `s3.amazon\images` (string, optional) - Path of the profile image of user on s3 Amazon.
- bio: `A computer technicain..` (string, optional) - Biography of user.
- birthdate: `March 3, 1994` (optional) - Birthdate of user.

## User Full
- id: `1hdfb3dfj779` (string, required) - The unique uuid of user.
- Include User Create
- created_at: `2015-01-07T14:03:43Z` (string, required) - ISO8601 date and time of when the user was created.